apiVersion: v1
kind: Secret
metadata:
  name: pricing-service-secrets
type: Opaque
data:
  SECRET_KEY: Y3J5cHRvX3RyYWNrZXJfc3VwZXJfc2VjcmV0X2tleQ==  # base64 for "crypto_tracker_super_secret_key"
  POSTGRES_PASSWORD: cHJpY2luZ19wYXNz  # base64 for "pricing_pass"
